JAdminInterface/JAdminInterface/Models/UCCEntities/DEMO_REQUESTS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAdminInterface.Models.UCCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO_REQUESTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEMO_REQUESTS()
        {
            this.DEF_CC = new HashSet<DEF_CC>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PKG_ID { get; set; }
        public Nullable<System.DateTime> Request_DateTime { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEF_CC> DEF_CC { get; set; }
        public virtual DEF_CUSTOMERS DEF_CUSTOMERS { get; set; }
        public virtual DEF_JPACKAGES DEF_JPACKAGES { get; set; }
        public virtual DemoRequestStatu DemoRequestStatu { get; set; }
    }
}

JAdminInterface/JAdminInterface/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAdminInterface.Controllers
{
    public class AdminHomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JAdminInterface/JAdminInterface/Controllers/ClientHomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JAdminInterface.Models.UCCEntities;
using PagedList;

namespace JAdminInterface.Controllers
{
    public class ClientHomeController : Controller
    {
        private UCCEntities db = new UCCEntities();

        // GET: ClientHome
        public ActionResult Index()
        {
            var dEF_CUSTOMERS = db.DEF_CUSTOMERS.
                                   Include(d => d.AspNetUser).
                                   Include(d => d.CUSTOMER_STATUS).
                                   Include(d => d.DEF_CC).
                                   Include(d => d.DEF_CC);
            return View(dEF_CUSTOMERS.ToList());
        }

        // GET: ClientHome/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            if (dEF_CUSTOMERS == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CUSTOMERS);
        }

        // GET: ClientHome/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName");
            return View();
        }

        // POST: ClientHome/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Rating,UserID,Status,Mobile,Address,Website,Email")] DEF_CUSTOMERS dEF_CUSTOMERS)
        {
            if (ModelState.IsValid)
            {
                db.DEF_CUSTOMERS.Add(dEF_CUSTOMERS);
                db.SaveChanges();
                return RedirectToAction("ClientsExplorer", "ManageCLient");
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CUSTOMERS.UserID);
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", dEF_CUSTOMERS.Status);
            return View(dEF_CUSTOMERS);
        }

        // GET: ClientHome/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            if (dEF_CUSTOMERS == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CUSTOMERS.UserID);
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", dEF_CUSTOMERS.Status);
            return View(dEF_CUSTOMERS);
        }

        // POST: ClientHome/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Rating,UserID,Status,Mobile,Address,Website,Email")] DEF_CUSTOMERS dEF_CUSTOMERS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dEF_CUSTOMERS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CUSTOMERS.UserID);
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", dEF_CUSTOMERS.Status);
            return View(dEF_CUSTOMERS);
        }

        // GET: ClientHome/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            if (dEF_CUSTOMERS == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CUSTOMERS);
        }

        // POST: ClientHome/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            db.DEF_CUSTOMERS.Remove(dEF_CUSTOMERS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AgentCallCentersList(int? pageNumber)
        {
            var customerCCList = db.DEF_CUSTOMERS.Single(c => c.ID == 1).DEF_CC.ToList().ToPagedList(pageNumber ?? 1, 8);
            return View(customerCCList);

        }

       

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JAdminInterface/JAdminInterface/Controllers/ManageClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JAdminInterface.Models.UCCEntities;
using PagedList;
using JAdminInterface.Models;
using JAdminInterface.Models.UCCViewModels;
using Newtonsoft.Json;
using JAdminInterface.Models.AltitudeIntegration;

namespace JAdminInterface.Controllers
{
    public class ManageClientController : Controller
    {
        private UCCEntities db = new UCCEntities();

        // GET: ManageClient
        public async Task<ActionResult> Index()
        {
            var dEF_CLIENT = db.DEF_CUSTOMERS.Include(d => d.AspNetUser);
            return View(await dEF_CLIENT.ToListAsync());
        }

        // GET: ManageClient/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CLIENT = await db.DEF_CUSTOMERS.FindAsync(id);
            if (dEF_CLIENT == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CLIENT);
        }

        // GET: ManageClient/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: ManageClient/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Name,Rating,UserID")] DEF_CUSTOMERS dEF_CLIENT)
        {
            if (ModelState.IsValid)
            {
                db.DEF_CUSTOMERS.Add(dEF_CLIENT);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CLIENT.UserID);
            return View(dEF_CLIENT);
        }

        // GET: ManageClient/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CLIENT = await db.DEF_CUSTOMERS.FindAsync(id);
            if (dEF_CLIENT == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CLIENT.UserID);
            return View(dEF_CLIENT);
        }

        // POST: ManageClient/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Name,Rating,UserID")] DEF_CUSTOMERS dEF_CLIENT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dEF_CLIENT).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CLIENT.UserID);
            return View(dEF_CLIENT);
        }

        // GET: ManageClient/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CLIENT = await db.DEF_CUSTOMERS.FindAsync(id);
            if (dEF_CLIENT == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CLIENT);
        }

        // POST: ManageClient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            DEF_CUSTOMERS dEF_CLIENT = await db.DEF_CUSTOMERS.FindAsync(id);
            db.DEF_CUSTOMERS.Remove(dEF_CLIENT);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");

        }


        public ActionResult ManageClientHome()
        {
            return View();
        }


        public ActionResult DemoRequests(int? pageNumber)
        {
            var demoRequests = db.sp_cc_requests().ToList().ToPagedList(pageNumber ?? 1, 8);
            return View(demoRequests);

        }
        /*  public ActionResult ManageDemoRequest(int DemoRequestID)
          {
              DEMO_REQUESTS demoRequest = db.DEMO_REQUESTS.Where(d => d.ID == DemoRequestID).Include(d => d.DEF_JPACKAGES).Include(d => d.DEF_CUSTOMERS).SingleOrDefault();

              return View(demoRequest);
          }
          */

        public string EditClient(int customerID, string customerName, string customerWebsite, string customerAddress, int customerRating, int customerStatus, string customerMobile) {
            DEF_CUSTOMERS client = db.DEF_CUSTOMERS.Find(customerID);
            client.Name = customerName;
            client.Website = customerWebsite;
            client.Rating = customerRating;
            client.Status = customerStatus;
            client.Address = customerAddress;
            client.Mobile = customerMobile;

            db.SaveChanges();

            return "1";
        }


        public ActionResult ManageDemoRequest(int DemoRequestID, int CustomerID)
        {

            DEMO_REQUESTS demoRequest = db.DEMO_REQUESTS.Where(d => d.ID == DemoRequestID).Include(d => d.DEF_JPACKAGES).Include(d => d.DEF_CUSTOMERS).Include(d => d.DEF_CC).SingleOrDefault();



            ViewBag.CustomerID = CustomerID;

            DEF_CUSTOMERS customer = db.DEF_CUSTOMERS.Single(c => c.ID == CustomerID);

            var industries = db.DefSkillsViews.Where(s => s.CategoryName.Equals("Industry"));

            List<DefSkillsSelectItem> insdustriesCheckList = new List<DefSkillsSelectItem>();

            foreach (DefSkillsView view in industries)
            {
                DefSkillsSelectItem skillItem = new DefSkillsSelectItem(view);
                insdustriesCheckList.Add(skillItem);
            }

            ViewBag.Industry = new SelectList(insdustriesCheckList, "ID", "SkillName");

            var TOSs = db.CC_TOS;

            ViewBag.TOS = new SelectList(TOSs, "TOS_ID", "TOS_Name");

            var clientPackages = db.DEF_JPACKAGES;

            ViewBag.DEF_JPACKAGES = new SelectList(clientPackages, "ID", "Name");

            var skills = db.DefSkillsViews;
            List<DefSkillsSelectItem> skillsCheckList = new List<DefSkillsSelectItem>();
            foreach (DefSkillsView view in skills)
            {
                DefSkillsSelectItem skillItem = new DefSkillsSelectItem(view);
                skillsCheckList.Add(skillItem);
            }

            ViewBag.Skills = skillsCheckList;

            ViewBag.Customer = customer;
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", customer.Status);

            return View("ManageDemoRequest", demoRequest);
        }


        [HttpPost]
        public ActionResult ManageDemoRequest(int? CustomerId, int DEF_JPACKAGES, string DID, int Industry, int TOS)
        {
            var industries = db.DefSkillsViews.Where(s => s.CategoryName.Equals("Industry"));

            List<DefSkillsSelectItem> insdustriesCheckList = new List<DefSkillsSelectItem>();

            foreach (DefSkillsView view in industries)
            {
                DefSkillsSelectItem skillItem = new DefSkillsSelectItem(view);
                insdustriesCheckList.Add(skillItem);
            }

            ViewBag.Industry = new SelectList(insdustriesCheckList, "ID", "SkillName");

            var TOSs = db.CC_TOS;

            ViewBag.TOS = new SelectList(TOSs, "TOS_ID", "TOS_Name");

            var clientPackages = db.DEF_JPACKAGES;

            ViewBag.DEF_JPACKAGES = new SelectList(clientPackages, "ID", "Name");

            List<DEF_SKILLS> skills = db.DEF_SKILLS.ToList();
            List<DefSkillsSelectItem> skillsCheckList = new List<DefSkillsSelectItem>();
            foreach (DefSkillsView view in industries)
            {
                DefSkillsSelectItem skillItem = new DefSkillsSelectItem(view);
                skillsCheckList.Add(skillItem);
            }

            ViewBag.Skills = skillsCheckList;
            DEF_CUSTOMERS customer = db.DEF_CUSTOMERS.Single(c => c.ID == CustomerId);
            ViewBag.Customer = customer;
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", customer.Status);

            return View();
        }

        public string CreateCallCenter(int CustomerID, int PackageID, string DID, int Industry, int TOS, int? CC_ID, string Name, string FurtherDetails, int? DemoRequestID)
        {
            int ccID = 0;
            if (CC_ID == -1)
            {
                // create new cc for the customer ...
                DEF_CC new_cc = new DEF_CC();
                new_cc.Creation_time = DateTime.Now;
                new_cc.CustomerID = CustomerID;
                new_cc.Industry = Industry;
                new_cc.DID = DID;
                new_cc.TOS = TOS;
                new_cc.PackageID = PackageID;
                new_cc.Name = Name;
                new_cc.FurtherDetails = FurtherDetails;
                new_cc.DemoRequestID = DemoRequestID;
                db.DEF_CUSTOMERS.SingleOrDefault(c => c.ID == CustomerID).DEF_CC.Add(new_cc);

                

                db.SaveChanges();
                ccID = new_cc.ID;
            }
            else {
                ccID = CC_ID.Value;

JAdminInterface/JAdminInterface/Views/ManageClient/AdminDashboard.cshtml
@{
    ViewBag.Title = "AdminDashboard";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<h2>Administrator Dashboard</h2>

JAdminInterface/JAdminInterface/Views/ManageClient/ClientShared.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - JAdmin Interface</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/AdminPage.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>




                @Html.ActionLink("Jathwa", "Index", "AdminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <!-- uncomment code for absolute positioning tweek see top comment in css -->
            <!-- <div class="absolute-wrapper"> </div> -->
            <!-- Menu -->
            <div class="side-menu">

                <nav class="navbar navbar-default" role="navigation" style="margin-top:40px">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <!-- Main Menu -->
                    <div class="side-menu-container">
                        <ul class="nav navbar-nav">
                            <li class="panel panel-default" id="dropdown">
                                <a data-toggle="collapse" href="#dropdown-lvl1">
                                    <img src="~/Content/themes/base/images/sidebar_client_icon.png" width="20" height="20" style="margin-right:15px"> <b>
    Manage Clients</b>
    <span class="caret" style="margin-left:15px"></span>
</a>
                                <div id="dropdown-lvl1" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <ul class="nav navbar-nav ">

                                            <li>
                                                <a href="~/ManageClient/ClientsExplorer">
                                                    <img src="~/Content/themes/base/images/sidebar_explore_icon.png" width="15" height="15" style="margin-right:15px"> Clients Explorer
                                                   
                                                </a>
                                            </li>

                                            <li>
                                                <a href="~/ClientHome/Create">
                                                    <img src="~/Content/themes/base/images/sidebar_plus_sign_icon.png" width="15" height="15" style="margin-right:15px"> Create Client
                                                </a>
                                            </li>
                                            <li>
                                                <a href="~/ManageClient/DemoRequests">
                                                    <img src="~/Content/themes/base/images/sidebar_pending_requests_icon.png" width="15" height="15" style="margin-right:15px"> Demo Requests
                                                </a>
                                            </li>
                                            <!-- Dropdown level 2 -->
                                            <li class="panel panel-default" id="dropdown">
                                                <a data-toggle="collapse" href="#dropdown-lvl2">
                                                    <img src="~/Content/themes/base/images/sidebar_explore_icon.png" width="15" height="15" style="margin-right:15px"> Clients Monitoring
                                                    <span class="caret"></span>
                                                </a>
                                                <div id="dropdown-lvl2" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <ul class="nav navbar-nav">
                                                            <li><a href="#">Link</a></li>
                                                            <li><a href="#">Link</a></li>
                                                            <li><a href="#">Link</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </li>


                                            <li class="panel panel-default" id="dropdown">
                                                <a data-toggle="collapse" href="#dropdown-lvl2">
                                                    <img src="~/Content/themes/base/images/sidebar_client_billing.png" width="15" height="15" style="margin-right:15px">Manage Client Billing
                                                    <span class="caret"></span>
                                                </a>
                                                <div id="dropdown-lvl2" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <ul class="nav navbar-nav">
                                                            <li><a href="#">Link</a></li>
                                                            <li><a href="#">Link</a></li>
                                                            <li><a href="#">Link</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </li>

                                        </ul>
                                    </div>
                                </div>
                            </li>
                            <li class="panel panel-default" id="dropdown">
                                <a data-toggle="collapse" href="#dropdown-manage-agents">
                                    <img src="~/Content/themes/base/images/sidebar_agent_icon.png" width="20" height="20" style="margin-right:15px;"> <b>Manage Agents</b>
                                    <span class="caret" style="margin-left:15px"></span>
                                </a>

                                <div id="dropdown-manage-agents" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <ul class="nav navbar-nav">
                                            <li>
                                                <a href="~/RegisteredAgentsList/ActiveAgents">
                                                    <img src="~/Content/themes/base/images/sidebar_explore_icon.png" width="15" height="15" style="margin-right:15px"> Active Agents Explorer

                                                </a>
                                            </li>

                                            <li class="panel panel-default" id="dropdown">
                                                <a data-toggle="collapse" href="#dropdown-agent-interview">
                                                    <img src="~/Content/themes/base/images/sidebar_client_billing.png" width="15" height="15" style="margin-right:15px"> Agent Interview
                                                    <span class="caret"></span>
                                                </a>

                                                <div id="dropdown-agent-interview" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <ul class="nav navbar-nav">
                                                            <li>
                                                                <a href="~/RegisteredAgentsList/CandidateAgents">
                                                                    <img src="~/Content/themes/base/images/sidebar_explore_icon.png" width="15" height="15" style="margin-right:15px"> Candidate Agents

                                                                </a>
                                                            </li>

                                                            <li>
                                                                <a href="~/RegisteredAgentsList/RejectedAgents">
                                                                    <img src="~/Content/themes/base/images/sidebar_explore_icon.png" width="15" height="15" style="margin-right:15px"> Rejected Agents

                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </li>

                                            <li class="panel panel-default" id="dropdown">
                                                <a data-toggle="collapse" href="#dropdown-agent-training">
                                                    <img src="~/Content/themes/base/images/sidebar_client_billing.png" width="15" height="15" style="margin-right:15px"> Agent Training
                                                    <span class="caret"></span>
                                                </a>

                                                <div id="dropdown-agent-training" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <ul class="nav navbar-nav">
                                                            <li>
                                                                <a href="~/RegisteredAgentsList/TrainingAgents">
                                                                    <img src="~/Content/themes/base/images/sidebar_explore_icon.png" width="15" height="15" style="margin-right:15px"> In-Training Agents

                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </li>


                            <li><a href="#"><img src="~/Content/themes/base/images/sidebar_settings_icon.png" width="20" height="20" style="margin-right:15px"> <b>Configurations</b></a></li>
                            <li><a href="#"><img src="~/Content/themes/base/images/sidebar_dashboard_icon.png" width="20" height="20" style="margin-right:15px"> <b>Admin Dashboard</b></a></li>


                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>

            </div>
            <!-- Main Content -->
            <div class="container-fluid">
                <div class="side-body" style="margin-top:50px">
                    @RenderBody()
                </div>
            </div>
        </div>


        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jathwa Ltd.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/JAdmin")
    @RenderSection("scripts", required: false)

</body>
</html>







<script src="~/Scripts/AdminPage.js"></script>

JAdminInterface/JAdminInterface/Views/ManageClient/Details.cshtml
@model JAdminInterface.Models.UCCEntities.DEF_CUSTOMERS

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DEF_CLIENT</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>