JAdminInterface/JAdminInterface/Controllers/CallCentersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JAdminInterface.Models.UCCEntities;
using JAdminInterface.Models.UCCViewModels;

namespace JAdminInterface.Controllers
{
    public class CallCentersController : Controller
    {
        private UCCEntities db = new UCCEntities();

        // GET: CallCenters
        public ActionResult Index()
        {
            var dEF_CC = db.DEF_CC.Include(d => d.CC_STATUS).Include(d => d.DEF_CUSTOMERS).Include(d => d.DEF_JPACKAGES).Include(d => d.DEMO_REQUESTS);
            return View(dEF_CC.ToList());
        }

        // GET: CallCenters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CC dEF_CC = db.DEF_CC.Find(id);
            if (dEF_CC == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CC);
        }

        // GET: CallCenters/Create
        public ActionResult Create()
        {
            ViewBag.Status_Id = new SelectList(db.CC_STATUS, "ID", "Name");
            ViewBag.TOS = new SelectList(db.CC_TOS, "TOS_ID", "TOS_NAME");
            ViewBag.CustomerID = new SelectList(db.DEF_CUSTOMERS, "ID", "Name");
            ViewBag.PackageID = new SelectList(db.DEF_JPACKAGES, "ID", "Name");
            ViewBag.DemoRequestID = new SelectList(db.DEMO_REQUESTS, "ID", "ID");
            ViewBag.Industry = new SelectList(db.Industries, "ID", "Name");
            return View();
        }

        // POST: CallCenters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,DID,Industry,CustomerID,Creation_time,TOS,PackageID,Name,FurtherDetails,Status_Id,DemoRequestID")] DEF_CC dEF_CC)
        {
            if (ModelState.IsValid)
            {
                db.DEF_CC.Add(dEF_CC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Status_Id = new SelectList(db.CC_STATUS, "ID", "Name", dEF_CC.Status_Id);
            ViewBag.TOS = new SelectList(db.CC_TOS, "TOS_ID", "TOS_NAME", dEF_CC.TOS);
            ViewBag.CustomerID = new SelectList(db.DEF_CUSTOMERS, "ID", "Name", dEF_CC.CustomerID);
            ViewBag.PackageID = new SelectList(db.DEF_JPACKAGES, "ID", "Name", dEF_CC.PackageID);
            ViewBag.DemoRequestID = new SelectList(db.DEMO_REQUESTS, "ID", "ID", dEF_CC.DemoRequestID);
            ViewBag.Industry = new SelectList(db.Industries, "ID", "Name", dEF_CC.Industry);
            return View(dEF_CC);
        }

        // GET: CallCenters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CC dEF_CC = db.DEF_CC.Find(id);
            if (dEF_CC == null)
            {
                return HttpNotFound();
            }
            ViewBag.Status_Id = new SelectList(db.CC_STATUS, "ID", "Name", dEF_CC.Status_Id);
            ViewBag.TOS = new SelectList(db.CC_TOS, "TOS_ID", "TOS_NAME", dEF_CC.TOS);
            ViewBag.CustomerID = new SelectList(db.DEF_CUSTOMERS, "ID", "Name", dEF_CC.CustomerID);
            ViewBag.PackageID = new SelectList(db.DEF_JPACKAGES, "ID", "Name", dEF_CC.PackageID);
            ViewBag.DemoRequestID = new SelectList(db.DEMO_REQUESTS, "ID", "ID", dEF_CC.DemoRequestID);
            ViewBag.Industry = new SelectList(db.Industries, "ID", "Name", dEF_CC.Industry);
            return View(dEF_CC);
        }

        // POST: CallCenters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,DID,Industry,CustomerID,Creation_time,TOS,PackageID,Name,FurtherDetails,Status_Id,DemoRequestID")] DEF_CC dEF_CC)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dEF_CC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Status_Id = new SelectList(db.CC_STATUS, "ID", "Name", dEF_CC.Status_Id);
            ViewBag.TOS = new SelectList(db.CC_TOS, "TOS_ID", "TOS_NAME", dEF_CC.TOS);
            ViewBag.CustomerID = new SelectList(db.DEF_CUSTOMERS, "ID", "Name", dEF_CC.CustomerID);
            ViewBag.PackageID = new SelectList(db.DEF_JPACKAGES, "ID", "Name", dEF_CC.PackageID);
            ViewBag.DemoRequestID = new SelectList(db.DEMO_REQUESTS, "ID", "ID", dEF_CC.DemoRequestID);
            ViewBag.Industry = new SelectList(db.Industries, "ID", "Name", dEF_CC.Industry);
            return View(dEF_CC);
        }

        // GET: CallCenters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CC dEF_CC = db.DEF_CC.Find(id);
            if (dEF_CC == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CC);
        }

        // POST: CallCenters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DEF_CC dEF_CC = db.DEF_CC.Find(id);
            db.DEF_CC.Remove(dEF_CC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditCallCenter(int ccID, int? CustomerID)
        {
            IEnumerable<DEF_CC> cc ;


            if (ccID != -1)
            {
                cc = db.DEF_CC.Where(c => c.ID == ccID);
                ViewBag.CustomerID = cc.First().DEF_CUSTOMERS.ID;
            }
            else {
                cc = new HashSet<DEF_CC>();
                ViewBag.CustomerID = CustomerID;
            }

        
            
            ViewBag.Status_Id = new SelectList(db.CC_STATUS, "ID", "Name");
            ViewBag.TOS = new SelectList(db.CC_TOS, "TOS_ID", "TOS_NAME");
            
            ViewBag.DEF_JPACKAGES = new SelectList(db.DEF_JPACKAGES, "ID", "Name");
            ViewBag.DemoRequestID = new SelectList(db.DEMO_REQUESTS, "ID", "ID");
            ViewBag.Industry = new SelectList(db.Industries, "ID", "Name");

            

            List<DefSkillsSelectItem> insdustriesCheckList = new List<DefSkillsSelectItem>();

            var industries = db.DefSkillsViews.Where(s => s.CategoryName.Equals("Industry"));

            foreach (DefSkillsView view in industries)
            {
                DefSkillsSelectItem skillItem = new DefSkillsSelectItem(view);
                insdustriesCheckList.Add(skillItem);
            }


            var skills = db.DefSkillsViews;
            List<DefSkillsSelectItem> skillsCheckList = new List<DefSkillsSelectItem>();
            foreach (DefSkillsView view in skills)
            {
                DefSkillsSelectItem skillItem = new DefSkillsSelectItem(view);
                skillsCheckList.Add(skillItem);
            }

            ViewBag.Skills = skillsCheckList;
            return View(cc);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JAdminInterface/JAdminInterface/Controllers/ClientHomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JAdminInterface.Models.UCCEntities;
using PagedList;

namespace JAdminInterface.Controllers
{
    public class ClientHomeController : Controller
    {
        private UCCEntities db = new UCCEntities();

        // GET: ClientHome
        public ActionResult Index()
        {
            var dEF_CUSTOMERS = db.DEF_CUSTOMERS.
                                   Include(d => d.AspNetUser).
                                   Include(d => d.CUSTOMER_STATUS).
                                   Include(d => d.DEF_CC).
                                   Include(d => d.DEF_CC);
            return View(dEF_CUSTOMERS.ToList());
        }

        // GET: ClientHome/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            if (dEF_CUSTOMERS == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CUSTOMERS);
        }

        // GET: ClientHome/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName");
            return View();
        }

        // POST: ClientHome/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Rating,UserID,Status,Mobile,Address,Website,Email")] DEF_CUSTOMERS dEF_CUSTOMERS)
        {
            if (ModelState.IsValid)
            {
                db.DEF_CUSTOMERS.Add(dEF_CUSTOMERS);
                db.SaveChanges();
                return RedirectToAction("ClientsExplorer", "ManageCLient");
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CUSTOMERS.UserID);
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", dEF_CUSTOMERS.Status);
            return View(dEF_CUSTOMERS);
        }

        // GET: ClientHome/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            if (dEF_CUSTOMERS == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CUSTOMERS.UserID);
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", dEF_CUSTOMERS.Status);
            return View(dEF_CUSTOMERS);
        }

        // POST: ClientHome/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Rating,UserID,Status,Mobile,Address,Website,Email")] DEF_CUSTOMERS dEF_CUSTOMERS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dEF_CUSTOMERS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", dEF_CUSTOMERS.UserID);
            ViewBag.Status = new SelectList(db.CUSTOMER_STATUS, "CustomerStatusID", "CustomerStatusName", dEF_CUSTOMERS.Status);
            return View(dEF_CUSTOMERS);
        }

        // GET: ClientHome/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            if (dEF_CUSTOMERS == null)
            {
                return HttpNotFound();
            }
            return View(dEF_CUSTOMERS);
        }

        // POST: ClientHome/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DEF_CUSTOMERS dEF_CUSTOMERS = db.DEF_CUSTOMERS.Find(id);
            db.DEF_CUSTOMERS.Remove(dEF_CUSTOMERS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AgentCallCentersList(int? pageNumber)
        {
            var customerCCList = db.DEF_CUSTOMERS.Single(c => c.ID == 1).DEF_CC.ToList().ToPagedList(pageNumber ?? 1, 8);
            return View(customerCCList);

        }

       

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JAdminInterface/JAdminInterface/Views/ClientHome/CallCentersListPartialView.cshtml
@using PagedList;

@using PagedList.Mvc;

@model IPagedList <JAdminInterface.Models.UCCEntities.DEF_CC>


<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Package</th>
            <th>DID</th>
            <th>Industry</th>
            <th>Type of Service</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;

            foreach (var item in Model)
            {

                using (Html.BeginForm("EditCallCenter", "CallCenters", FormMethod.Get))
                {
                    @Html.AntiForgeryToken()
                    <tr>
                        <th scope="row">@i</th>

                        <td>@item.Name</td>
                        <td>@item.DEF_JPACKAGES.Name</td>
                        <td>@item.DID</td>
                        <td>@item.Industry</td>
                        <td>@item.CC_TOS.TOS_NAME</td>
                        <input type="hidden" value="@item.ID" name="ccID" />
                        <td><input type="submit" value="Edit" id="@item.ID" name="edit" class="btn btn-default"></td>
                    </tr>


                }

                i++;
            }

        }
    </tbody>
</table>

<div style="text-align:center">
    @Html.PagedListPager(Model, pageNumber => Url.Action("AgentCallCentersList", new
    {
        pageNumber
    }))

</div>

JAdminInterface/JAdminInterface/Views/ClientHome/Create.cshtml
@model JAdminInterface.Models.UCCEntities.DEF_CUSTOMERS

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><b style="font-size:larger">Create New Client</b></div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            
            <br/>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
                </div>
            </div>

           

            <div class="form-group">
                @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

JAdminInterface/JAdminInterface/Views/ClientHome/Delete.cshtml
@model JAdminInterface.Models.UCCEntities.DEF_CUSTOMERS

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DEF_CUSTOMERS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CUSTOMER_STATUS.CustomerStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUSTOMER_STATUS.CustomerStatusName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JAdminInterface/JAdminInterface/Views/ClientHome/Details.cshtml
@using JAdminInterface.Models.UCCEntities
@using JAdminInterface.Models
@using PagedList;

@using PagedList.Mvc;
@model JAdminInterface.Models.UCCEntities.DEF_CUSTOMERS


@{
    ViewBag.Title = "Details";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}



<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><b style="font-size:larger">Basic Information</b></div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>


        <dt>
            Status
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUSTOMER_STATUS.CustomerStatusName)
        </dd>

    </dl>
</div>




<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><b style="font-size:larger">Call Centers List</b></div>
    <br />
    @{
        var ccList = Model.DEF_CC.ToList().ToPagedList(1, 8);
        @Html.Partial("CallCentersListPartialView", ccList);
    }

    @using (Html.BeginForm("EditCallCenter", "CallCenters", FormMethod.Get))
    {

    <div style="text-align:center;margin-top:10px">
        <input type="hidden" value="-1" name="ccID" />
        <input type="hidden" value="@Model.ID" name="CustomerID" id="CustomerId"/>
        <input type="submit" value="Create New Call Center" class="btn btn-success" style="margin-left:10px;margin-bottom:10px" />
    </div>
    }





    </div>

JAdminInterface/JAdminInterface/Views/ClientHome/Edit.cshtml
@model JAdminInterface.Models.UCCEntities.DEF_CUSTOMERS

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DEF_CUSTOMERS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>