JAdminInterface/JAdminInterface/Controllers/RegisteredAgentsListController.cs
using JAdminInterface.Models.UCCEntities;
using JAdminInterface.Models.UCCViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using JAdminInterface.Models;
using Microsoft.AspNet.Identity;
using System.Data.SqlClient;
using JAdminInterface.Shared;
using PagedList;


namespace JAdminInterface.Controllers
{

    [Authorize]
    public class RegisteredAgentsListController : Controller
    {
        private  UCCEntities db = new UCCEntities();



        // GET: RegisteredAgents
        public ActionResult Index(int? pageNumber)
        {

           
            var result = db.Database
                .SqlQuery<sp_registered_agents_list_Result>("sp_registered_agents_list")
                .ToList().ToPagedList(pageNumber ?? 1, 10);

            

            return View(result);
        }


        public ActionResult RegisteredAgentInterview(int? AgentID)
        {
            /*  if (AgetnID == null)
              {
                  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
              }
              */

           

            DEF_AGENT registeredAgent = db.DEF_AGENT.Where(a => a.ID == AgentID).First();


            return View(registeredAgent);
        }

       
        public ActionResult ScheduleAgentInterview(int? AgentID)
        {
            List<AspNetUser> adminUsers = db.AspNetUsers.Where(u => u.AspNetRoles.Any(r => r.Name.Equals("Admin"))).ToList();

            ViewData["Users"] = adminUsers;
            
            DEF_AGENT agentEntity = db.DEF_AGENT.Where(e => e.ID == AgentID).SingleOrDefault();
            
            ScheduleInterviewViewModel scheduleViewModel = new ScheduleInterviewViewModel();

            scheduleViewModel.agent = agentEntity;
            
            return View(scheduleViewModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ScheduleAgentInterview(FormCollection Form)
        {
            // Schedule the interview .. 
            int AgentID = int.Parse(Form["agent.ID"]);
            string ScheduledToUserID = Form["ScheduleToUser"];

            string ScheduledByUserID = System.Web.HttpContext.Current.User.Identity.GetUserId();


            DateTime ScheduleDate  = DateTime.Parse(Form["ScheduleDate"]);

            AGENT_INTERVIEW interview = db.AGENT_INTERVIEW.Where(i => i.AgentId == AgentID).SingleOrDefault();
            interview.AGENT_INTERVIEW_STATUSES = db.AGENT_INTERVIEW_STATUSES.Where(s => s.InterviewStatusName.Equals("Scheduled")).SingleOrDefault();

            // First deactivate any previouse schdeules on this interview ..
            var previouseSchedules = interview.AGENT_INTERVIEW_SCHEDULES.Where(s => s.INTERVIEW_SCHEDULE_STATUS.ScheduleStatusName.Equals("Active Schedule")).ToList();
            foreach (AGENT_INTERVIEW_SCHEDULES schedule in previouseSchedules) {
                schedule.INTERVIEW_SCHEDULE_STATUS = db.INTERVIEW_SCHEDULE_STATUS.Single(x => x.ScheduleStatusName.Equals("Inactive Schedule"));
            }
            
            // Create a new shedule ..

            AGENT_INTERVIEW_SCHEDULES interviewSchedule = new AGENT_INTERVIEW_SCHEDULES();
            interviewSchedule.ScheduledBy = ScheduledByUserID;
            interviewSchedule.ScheduledTo = ScheduledToUserID;
            interviewSchedule.ScheduleDate = ScheduleDate;
            interviewSchedule.CreationDate = DateTime.Now;
            interviewSchedule.INTERVIEW_SCHEDULE_STATUS= db.INTERVIEW_SCHEDULE_STATUS.Where(s => s.ScheduleStatusName.Equals("Active Schedule")).SingleOrDefault();

            interview.AGENT_INTERVIEW_SCHEDULES.Add(interviewSchedule);

            try
            {
                db.SaveChanges();
                // send notification email to the admnin for training
                EmailNotificationSender.SendMail(
                            "hossam.farag.mohammed@gmail.com",
                            "hossam.farag.mohammed@gmail.com",
                            "Jathwa Notification, Agent Interview Schedule",
                            "Hi Mr. Admin, You have been assigned to a scheduled agent interview on: " + interviewSchedule.ScheduleDate.ToShortDateString(),
                            "HIGH");


                
            }
            catch (Exception e) {
                Console.Write(e.Message);
            }
            


            return RedirectToAction("AdminWelcomePage");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisteredAgentInterview(FormCollection Form)
        {
           
            // Prepare interview data ..
            int agentId = int.Parse(Form["ID"]);
            string userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            string interviewStatus = "";

            DEF_AGENT agent = db.DEF_AGENT.Include(s => s.AGENT_SKILL).Where(a => a.ID == agentId).First();
            AspNetUser user = db.AspNetUsers.Where(u => u.Id == userId).First();

           
            string overall_score = "", evaluation_comments = "";


            if (ModelState.IsValid)
            {
                foreach (string key in Form.AllKeys)
                {

                    // Get list of skills and assigned scores ..
                    if (key.EndsWith("-score_text_box"))
                    {

                        string skillID = (key.Split(new char[] { '-' })[0]);


                        INTERVIEW_DETAILS interviewDetail = agent.AGENT_INTERVIEW.First().INTERVIEW_DETAILS.Where(s => s.SkillId == int.Parse(skillID)).First();
                        interviewDetail.Score = double.Parse(Form[key]);
                    }
                    else if (key.Equals("evaluation_text_box"))
                    {
                        overall_score = Form[key];
                    }
                    else if (key.Equals("comments_text_area"))
                    {
                        evaluation_comments = Form[key];
                    }
                    else if (key.Equals("button"))
                    {
                        interviewStatus = Form[key];
                        
                    }
                }

                AGENT_INTERVIEW agentInterview = agent.AGENT_INTERVIEW.First();

                agentInterview.AspNetUser = user;
                agentInterview.InterviewComments = evaluation_comments;

                agentInterview.AGENT_INTERVIEW_STATUSES = db.AGENT_INTERVIEW_STATUSES.Where(s => s.InterviewStatusName.Equals(interviewStatus)).SingleOrDefault();

                try
                {
                    db.SaveChanges();

                    // send notification email to the admnin for training
                    EmailNotificationSender.SendMail(
                            "hossam.farag.mohammed@gmail.com",
                            "hossam.farag.mohammed@gmail.com",
                            "Jathwa Notification, Agent Interview Status review",
                            "Hi Mr. Admin, A new agent interview is submitted to the system",
                            "HIGH");

                }
                catch (Exception ex)
                {
                    Console.Write(ex.Message);
                    throw;
                }



                if (interviewStatus.Equals("Accepted"))
                {
                   // agent.AGENT_STATUS = db.AGENT_STATUS.Single(s => s.AgentStatusName.Equals("RFT"));
                   

                    string sql = "exec sp_move_agent_skills @AgentID = @AgentID_Param";
                    
                    var parameters = new[]{
                        new SqlParameter("@AgentID_Param", agent.ID) };

                    db.Database.SqlQuery<object>(sql, parameters).ToList();

                    db.SaveChanges();

                    return RedirectToAction("AssignCallCenters", agentInterview);
                }
                else if (interviewStatus.Equals("Save & Reschedule")) {
                    return RedirectToAction("ScheduleAgentInterview", new { AgentID = agent.ID });
                }
                else
                {
                    //agent.AGENT_STATUS = db.AGENT_STATUS.Single(s => s.AgentStatusName.Equals("Rejected"));

                    //db.SaveChanges();
                    return RedirectToAction("AdminWelcomePage");
                }
                
               // return RedirectToAction("AssignCallCenters");

            }

            return RedirectToAction("AdminWelcomePage");



        }




        public ActionResult AssignCallCenters(AGENT_INTERVIEW interview)
        {
            // refetch from DB because related objects are not passed while calling th function

            interview = db.AGENT_INTERVIEW.Where(i => i.Id == interview.Id)
                                          .Include(s => s.AGENT_INTERVIEW_STATUSES)
                                          .Include(s => s.DEF_AGENT)
                                          .Include(s => s.INTERVIEW_DETAILS)
                                          .SingleOrDefault();



            IEnumerable<DEF_CC> cc_list = db.DEF_CC.ToArray();

            ViewData["CC_LIST"] = cc_list;

            return View(interview);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AssignCallCenters(FormCollection formCollection)
        {
            int AgentID = 0;
            AGENT_INTERVIEW agent_interview = null;
            if (ModelState.IsValid)
            {


                int interviewID;
                
                int[] cc_id_list;

                foreach (string key in formCollection.AllKeys)
                {
                    if (key.Equals("InterviewID"))
                    {

                        interviewID = int.Parse(formCollection[key]);

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/ActiveAgents.cshtml
@using PagedList;

@using PagedList.Mvc;
@model IPagedList<JAdminInterface.Models.UCCEntities.sp_active_agents_Result>

@{
    ViewBag.Title = "ActiveAgents";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><b style="font-size:larger">Active Agents</b></div>

    <!-- Table -->
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Agent ID
                </th>
                <th>
                    Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Phone
                </th>

                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AgentID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AgentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AgentEmailAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AgentPhoneNumber)
                </td>

                <td>
                    @Html.ActionLink("View Details", "ViewAgentInterview", new { AgentID = item.AgentID })

                </td>
            </tr>
    }

        </tbody>
    </table>
</div>


<br>

<div style="text-align:center">
    @Html.PagedListPager(Model, pageNumber => Url.Action("ActiveAgents", new
    {
        pageNumber
    }))

</div>

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/AdminWelcomePage.cshtml
@{
    ViewBag.Title = "AdminWelcomePage";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<h2>Jathwa Admin Control Panel</h2>



<br><br><br>

<div class="container" style="margin-top:150px">
    <div class="row">
        <div class="col-sm-3  col-xs-6 ">
            <div class="AdminWelcomeTile lg">
                <a href="~/RegisteredAgentsList/ActiveAgents"><img src="~/Content/themes/base/images/active.png" title="Active Agents" class="img-responsive center-block AdminTileImg" /></a>
                <div class="img_title one">
                    Active Agents
                </div>
            </div>
        </div>

        <div class="col-sm-3 col-xs-6">
            <div class="AdminWelcomeTile">
                <a href="~/RegisteredAgentsList/CandidateAgents"><img src="~/Content/themes/base/images/candidate.png" title="Candidate Agents" class="img-responsive center-block AdminTileImg" /></a>
                <div class="img_title two">
                    Candidate Agents
                </div>
            </div>
        </div>

        <div class="col-sm-3  col-xs-6">
            <div class="AdminWelcomeTile">
                <a href="~/RegisteredAgentsList/TrainingAgents"><img src="~/Content/themes/base/images/in-training.png" title="In-Training Agents" class="img-responsive center-block AdminTileImg" /></a>
                <div class="img_title three">
                    Training Agents
                </div>
            </div>
        </div>

        <div class="col-sm-3 col-xs-6">
            <div class="AdminWelcomeTile">
                <a href="~/RegisteredAgentsList/RejectedAgents"><img src="~/Content/themes/base/images/rejected.png" title="Rejected Agents" class="img-responsive center-block AdminTileImg" /></a>
                <div class="img_title four">
                    Rejected Agents
                </div>
            </div>
        </div>

    </div>
</div>


</div>

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/AssignCallCenters.cshtml
@model JAdminInterface.Models.UCCEntities.AGENT_INTERVIEW


@{
    ViewBag.Title = "AssignCallCenters";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<h2>Assign Call Centers</h2>

<div>

    <h4>Agent Interview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Agent Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DEF_AGENT.Name)
        </dd>

        
      

        <dt>
            Interview Comments
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewComments)
        </dd>

        <dt>
            Interview Status
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AGENT_INTERVIEW_STATUSES.InterviewStatusName)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>



    </dl>


    <br/><br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.Hidden("InterviewID", Model.Id)

        <div class="form-group">
            <table class="table">
                <tr>
                    <th>
                        DID
                    </th>
                    <th>
                        Industry
                    </th>
                    <th>
                        Customer
                    </th>
                    <th>
                        Allocated Agents
                    </th>
                    <th>
                        Assign
                    </th>
                </tr>



                @foreach (JAdminInterface.Models.UCCEntities.DEF_CC call_center in ViewBag.CC_LIST)
                {
                <tr>
                    <td>
                        @call_center.DID
                    </td>
                    <td>
                        @call_center.DEF_SKILLS.Name
                    </td>
                    <td>
                        @call_center.DEF_CUSTOMERS.Name
                    </td>
                    <td>
                        @call_center.AGENT_CALL_CENTERS.Count
                    </td>



                    <td>

                        <input type="checkbox"
                               name="call_centers_checkbox"
                               value="@call_center.ID" class="form-group" />


                    </td>
                </tr>

                }
            </table>


            <div class="form-group">
                <div >
                    <input type="submit" value="Proceed" class="btn btn-success" />
                </div>
            </div>
        </div>




    }

</div>

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/CandidateAgents.cshtml
@using PagedList;

@using PagedList.Mvc;
@model IPagedList<JAdminInterface.Models.UCCEntities.sp_candidate_agents_Result>

@{
    /**/

    ViewBag.Title = "CandidateAgents";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"><b style="font-size:larger">Candidate Agents</b></div>

    <div class="panel-body">

        <!-- Table -->
        <table class="table table-striped">
            <thead>


                <tr>
                    <th class="block">
                        Agent ID
                    </th>
                    <th class="block">
                        Name
                    </th>

                    <th class="block">
                        Interview Status
                    </th>

                    <th class="block">
                        Schedule By
                    </th>

                    <th class="block">
                        Schedule To
                    </th>
                    <th class="block">
                        Schedule Date
                    </th>
                    <th>Action</th>
                    <th>Action2</th>
                </tr>

            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.AgentID)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.AgentPhoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InterviewStatus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ScheduledByUserName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.ScheduledToUserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ScheduleDate)
                        </td>


                        <td>

                            @if (item.InterviewStatus.Equals("Accepted") || item.InterviewStatus.Equals("Rejected"))
                            {
                                @Html.ActionLink("View Details", "ViewAgentInterview", new { AgentID = item.AgentID })
                            }
                            else if (item.InterviewStatus.Equals("Scheduled"))
                            {
                                @Html.ActionLink("Reschedule Interview", "ScheduleAgentInterview", new { AgentID = item.AgentID })
                            }
                            else if (item.InterviewStatus.Equals("Initiated"))
                            {
                                @Html.ActionLink("Schedule Interview", "ScheduleAgentInterview", new { AgentID = item.AgentID })
                            }




                        </td>
                        @if (!item.InterviewStatus.Equals("Accepted") & !item.InterviewStatus.Equals("Rejected"))
                        {
                            <td>
                                @Html.ActionLink("Start Interview", "RegisteredAgentInterview", new { AgentID = item.AgentID })
                            </td>
                        }
                        else {
                            <td></td>
                        }



                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

    <div style="text-align:center">
        @Html.PagedListPager(Model, pageNumber => Url.Action("CandidateAgents", new
        {
            pageNumber
        }))

    </div>

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/Index.cshtml
@using PagedList;

@using PagedList.Mvc;
@model IPagedList<JAdminInterface.Models.UCCEntities.sp_registered_agents_list_Result>


@{
    ViewBag.Title = "Applicant Agent";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<h2>Applicant Agents</h2>

<br />


<table class="table">
    <tr>
        <th>
            Agent ID
        </th>
        <th>
            Agent Name
        </th>
        <th>
            Phone
        <th>
            Email
        </th>

        <th>
            Interview Status
        </th>

        <th>
            Scheduled By
        </th>
        <th>
            Scheduled To
        </th>
        <th>
            Schedule Date
        </th>
        <th>

        </th>
        <th>

        </th>


    </tr>




    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AgentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgentPhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgentEmailAddress)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.InterviewStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScheduledByUserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScheduledToUserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScheduleDate)
            </td>

            <td></td>

            <td>

                @if (item.InterviewStatus.Equals("Accepted") || item.InterviewStatus.Equals("Rejected"))
                {
                    @Html.ActionLink("View Interview", "ViewAgentInterview", new { AgentID = item.AgentID })
                }
                else if (item.InterviewStatus.Equals("Scheduled"))
                {
                    @Html.ActionLink("Reschedule Interview", "ScheduleAgentInterview", new { AgentID = item.AgentID })
                }
                else if (item.InterviewStatus.Equals("Initiated"))
                {
                    @Html.ActionLink("Schedule Interview", "ScheduleAgentInterview", new { AgentID = item.AgentID })
                }




            </td>
            @if (!item.InterviewStatus.Equals("Accepted") & !item.InterviewStatus.Equals("Rejected"))
            {
                <td>
                    @Html.ActionLink("Start Interview", "RegisteredAgentInterview", new { AgentID = item.AgentID })
                </td>
            }

        </tr>
    }

</table>


<div style="text-align:center">
    @Html.PagedListPager(Model, pageNumber => Url.Action("Index", new
    {
        pageNumber
    }))

</div>

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/RegisteredAgentInterview.cshtml
@model JAdminInterface.Models.UCCEntities.DEF_AGENT

@{
    ViewBag.Title = "RegisteredAgentInterview";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";

}

<h2>Agent Interview</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Agent Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Phone
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobNo)
        </dd>



        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            Gender
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GENDER1.GenderName)
        </dd>

        <dt>
            Nationality
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NATIONALITY1.Name)
        </dd>

        

    </dl>


</div>

<br /><br />

<div class="form-horizontal">
    @Html.Label("Interview status", new { @class = "control-label col-md-2" })
    @Html.Label(Model.AGENT_INTERVIEW.First().AGENT_INTERVIEW_STATUSES.InterviewStatusName, new { @class = "form-control" })

</div>


@using (Html.BeginForm("RegisteredAgentInterview", "RegisteredAgentsList", FormMethod.Post, new { id = "agentForm" }))
{
    @Html.AntiForgeryToken()



    <br /><br /><br />

    <div>

        <h4>Agent Skills</h4>
        @Html.HiddenFor(model => model.ID)
        <table class="table">
            <tr>
                <th>
                    Skill
                </th>
                <th>
                    Score
                </th>

            </tr>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @for (int i = 0; i < Model.AGENT_INTERVIEW.First().INTERVIEW_DETAILS.Count; i++)
            {
                <tr>
                    <td>
                        @Model.AGENT_INTERVIEW.First().INTERVIEW_DETAILS.ToList()[i].DEF_SKILLS.Name
                    </td>
                    <td>


                        <input id="@Model.AGENT_INTERVIEW.First().INTERVIEW_DETAILS.ToList()[i].SkillId" name="@Model.AGENT_INTERVIEW.First().INTERVIEW_DETAILS.ToList()[i].SkillId-score_text_box" class="form-control xyz" type="number" value=@Model.AGENT_INTERVIEW.First().INTERVIEW_DETAILS.ToList()[i].Score />
                        <span class="agentMSG-@Model.AGENT_INTERVIEW.First().INTERVIEW_DETAILS.ToList()[i].SkillId text-danger"></span>




                    </td>
                </tr>


            }


        </table>

        <div>
            <h4>Overall Evaluation</h4>

            <br />

            <div class="form-group">
                @Html.Label("Comments")
                @Html.TextArea("comments_text_area", @Model.AGENT_INTERVIEW.First().InterviewComments, new { @class = "form-control" })
            </div>


            @*

                @{var items = new List<SelectListItem>()
                {
                    new SelectListItem{ Text="Accepted", Value = "Accepted" },
                    new SelectListItem{ Text="Rejected", Value = "Rejected" },
                    new SelectListItem{ Text="Decide Later", Value = "In Progress" },
                };

                    }




                    <div class="form-group">
                        @Html.Label("Interview Status")
                        @Html.DropDownList("interview_status_droplist", items, new { @class = "form-control" })

                    </div>

            *@
            <div class="btn-group-lg">
                <div>
                    <input name="button" type="submit" value="Accepted" class="btn btn-success" />
                    <input name="button" type="submit" value="Rejected" class="btn btn-danger" />
                    <input name="button" type="submit" value="Save & Reschedule" class="btn btn-warning" />

                </div>

            </div>





        </div>
    </div>


}

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/RegisteredAgentLayout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>

</head>
<body>


    <h1>AgentLayoutHeader</h1>





</body>
</html>

JAdminInterface/JAdminInterface/Views/RegisteredAgentsList/ScheduleAgentInterview.cshtml
@model JAdminInterface.Models.UCCViewModels.ScheduleInterviewViewModel

@{
    ViewBag.Title = "Schedule Agent Interview";
    Layout = "~/Views/ManageClient/ClientShared.cshtml";
}

<div>

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><b style="font-size:larger">Agent Details</b></div>

        <div class="panel-body">
            <br />
            <dl class="dl-horizontal">
                <dt>
                    Agent Name
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.agent.Name)
                </dd>

                <dt>
                    Mobile
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.agent.MobNo)
                </dd>



                <dt>
                    Email
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.agent.AspNetUser.Email)
                </dd>

                <dt>
                    Gender
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.agent.GENDER1.GenderName)
                </dd>

                <dt>
                    Nationality
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.agent.NATIONALITY1.Name)
                </dd>

            </dl>
        </div>
    </div>
</div>




@using (Html.BeginForm(Html.BeginForm("ScheduleAgentInterview", "RegisteredAgentsList", FormMethod.Post, new { id = "scheduleForm" })))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><b style="font-size:larger">Schedule Details</b></div>

        <div class="panel-body">

            <div class="form-horizontal">

                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.agent.ID)

                <div class="form-group">
                    @Html.Label("Schedule To User", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        @{
                            var items = new List<SelectListItem>();


                            foreach (JAdminInterface.Models.UCCEntities.AspNetUser user in ViewBag.Users)
                            {

                                SelectListItem item = new SelectListItem { Text = user.Email, Value = user.Id };
                                items.Add(item);
                            }

                        }


                        @Html.DropDownList("ScheduleToUser", items, new { @class = "form-control" })

                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Schedule Date", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        <input class="form-control datepicker" name="ScheduleDate" type="text">

                        @Html.ValidationMessageFor(model => model.ScheduleDate, "", new { htmlAttributes = new { @class = "text-danger" } })
                    </div>




                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>

            </div>




        </div>
    </div>
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")



}